x-airflow-common:
  &airflow-common
  image: apache/airflow:2.10.5
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
    AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW__CORE__LOAD_EXAMPLES}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: ${AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION}
    AIRFLOW__API__AUTH_BACKENDS: ${AIRFLOW__API__AUTH_BACKENDS}
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    AIRFLOW_UID: ${AIRFLOW_UID}
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    AWS_REGION: ${AWS_REGION}
    KAGGLE_CONFIG_DIR: /opt/airflow/secrets
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/config:/opt/airflow/config
    - ./ingestion:/opt/airflow/ingestion
    - ./spark:/opt/airflow/spark
    - ./scripts:/opt/airflow/scripts
    - ./data:/opt/airflow/data
    - ./.env:/opt/airflow/.env
    - ./requirements.txt:/requirements.txt
    - ./secrets:/opt/airflow/secrets
    - /var/run/docker.sock:/var/run/docker.sock
  user: "${AIRFLOW_UID}:0"
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:16
    container_name: retail_lakehouse_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  airflow-init:
    <<: *airflow-common
    container_name: retail_lakehouse_airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pip install --no-cache-dir -r /requirements.txt &&
        airflow db migrate &&
        airflow users create \
          --username admin \
          --password admin \
          --firstname Thiago \
          --lastname Souza \
          --role Admin \
          --email admin@retail-lakehouse.local
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    container_name: retail_lakehouse_airflow_webserver
    command: >
      bash -c "pip install --no-cache-dir -r /requirements.txt &&
      airflow webserver"
    ports:
      - "8088:8080"
    restart: unless-stopped

  airflow-scheduler:
    <<: *airflow-common
    container_name: retail_lakehouse_airflow_scheduler
    command: >
      bash -c "pip install --no-cache-dir -r /requirements.txt &&
      airflow scheduler"
    restart: unless-stopped

  spark:
    image: apache/spark:3.5.1-python3
    container_name: retail_lakehouse_spark
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_REGION: ${AWS_REGION}
    volumes:
      - ./spark:/opt/spark-apps
      - ./data:/data
      - ./.env:/opt/spark-apps/.env
    command: >
      /bin/bash -c "/opt/spark/sbin/start-master.sh && tail -f /dev/null"
    ports:
      - "4040:4040"
      - "7077:7077"
      - "8081:8080"
    restart: unless-stopped

volumes:
  postgres_db_volume: